# Generated by Django 5.1.7 on 2025-03-18 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_fookal'),
    ]

    operations = [
        migrations.DeleteModel(
            name='fookal',
        ),
    ]
