# Generated by Django 5.1.7 on 2025-03-18 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_delete_fookal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athlete',
            name='bib_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
