# Generated by Django 5.1.7 on 2025-03-19 20:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0007_remove_payment_billing_address_1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='racepackage',
            name='race',
        ),
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='events/'),
        ),
        migrations.AddField(
            model_name='event',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='event',
            name='location',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='racepackage',
            name='event',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='event.event'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='racepackage',
            name='races',
            field=models.ManyToManyField(related_name='packages', to='event.race'),
        ),
        migrations.CreateModel(
            name='PackageOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('choices', models.CharField(blank=True, max_length=255, null=True)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='event.racepackage')),
            ],
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
