# Generated by Django 5.1.7 on 2025-03-19 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0008_remove_racepackage_race_event_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='packageoption',
            name='choices',
        ),
        migrations.AddField(
            model_name='packageoption',
            name='choices_json',
            field=models.TextField(blank=True, null=True),
        ),
    ]
