# Generated by Django 5.1.7 on 2025-03-19 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0009_remove_packageoption_choices_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='athlete',
            name='selected_options',
            field=models.TextField(blank=True, null=True),
        ),
    ]
