# Generated by Django 5.1.7 on 2025-03-29 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0010_athlete_selected_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='packageoption',
            name='choices_json',
        ),
        migrations.AddField(
            model_name='packageoption',
            name='choices',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='selected_options',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
