# Generated by Django 5.1.7 on 2025-03-29 19:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0011_remove_packageoption_choices_json_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='packageoption',
            name='choices',
        ),
        migrations.AddField(
            model_name='packageoption',
            name='options_json',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='packageoption',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.racepackage'),
        ),
    ]
