# Generated by Django 5.1.7 on 2025-03-29 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0012_remove_packageoption_choices_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='packageoption',
            name='options_string',
            field=models.CharField(blank=True, editable=False, max_length=500, null=True),
        ),
    ]
