# Generated by Django 5.1.7 on 2025-03-30 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0013_packageoption_options_string'),
    ]

    operations = [
        migrations.AddField(
            model_name='race',
            name='min_participants',
            field=models.PositiveIntegerField(blank=True, help_text='Minimum number of participants required for the race.', null=True),
        ),
    ]
