# Generated by Django 5.1.7 on 2025-03-30 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0014_race_min_participants'),
    ]

    operations = [
        migrations.AddField(
            model_name='race',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
