# Generated by Django 5.1.7 on 2025-03-31 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0015_race_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='athlete',
            name='selected_options',
        ),
        migrations.AddField(
            model_name='athlete',
            name='selected_options',
            field=models.ManyToManyField(blank=True, to='event.packageoption'),
        ),
    ]
