# Generated by Django 5.1.7 on 2025-04-01 07:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0017_remove_athlete_selected_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='event',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='event.event'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='athlete',
            name='selected_options',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='packageoption',
            name='options_json',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddConstraint(
            model_name='racepackage',
            constraint=models.UniqueConstraint(fields=('event', 'name'), name='unique_package_per_event'),
        ),
    ]
