# Generated by Django 5.1.7 on 2025-04-03 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0018_registration_event_alter_athlete_selected_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='max_participants',
            field=models.PositiveIntegerField(blank=True, help_text='Maximum number of participants allowed for the event.', null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='registration_end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='registration_start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='race',
            name='max_participants',
            field=models.PositiveIntegerField(blank=True, help_text='Maximum number of participants required for the race.', null=True),
        ),
    ]
