# Generated by Django 5.1.7 on 2025-04-03 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0019_event_max_participants_event_registration_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='athlete',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
    ]
