# Generated by Django 5.1.7 on 2025-04-03 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0020_athlete_dob'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='athlete',
            name='age',
        ),
    ]
