# Generated by Django 5.1.7 on 2025-04-04 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0021_remove_athlete_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='max_participants',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='race',
            name='max_participants',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='race',
            name='min_participants',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
