# Generated by Django 5.1.7 on 2025-04-04 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0023_remove_packageoption_options_string'),
    ]

    operations = [
        migrations.AddField(
            model_name='packageoption',
            name='options_string',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
