# Generated by Django 5.1.7 on 2025-04-04 20:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0024_packageoption_options_string'),
    ]

    operations = [
        migrations.CreateModel(
            name='PickUpPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('working_hours', models.CharField(help_text='e.g. Mon–Fri 9am–5pm', max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='athlete',
            name='pickup_point',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='athletes', to='event.pickuppoint'),
        ),
    ]
