# Generated by Django 5.1.7 on 2025-04-04 20:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0025_pickuppoint_athlete_pickup_point'),
    ]

    operations = [
        migrations.AddField(
            model_name='pickuppoint',
            name='event',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='pickup_points', to='event.event'),
            preserve_default=False,
        ),
    ]
