# Generated by Django 5.1.7 on 2025-04-05 18:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0026_pickuppoint_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='athlete',
            name='agrees_to_terms',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='TermsAndConditions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Terms and Conditions', max_length=255)),
                ('content', models.TextField(help_text='You can use basic HTML or markdown.')),
                ('version', models.CharField(default='1.0', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='terms', to='event.event')),
            ],
        ),
        migrations.AddField(
            model_name='athlete',
            name='agreed_to_terms',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agreements', to='event.termsandconditions'),
        ),
    ]
