# Generated by Django 5.1.7 on 2025-04-06 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0027_athlete_agrees_to_terms_termsandconditions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/event_images/'),
        ),
    ]
