# Generated by Django 5.1.7 on 2025-04-08 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0029_event_organizer'),
    ]

    operations = [
        migrations.AddField(
            model_name='athlete',
            name='team',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
