# Generated by Django 5.1.7 on 2025-04-09 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0031_payment_alter_athlete_options_registration_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackageSpecialPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='event.event')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='special_prices', to='event.racepackage')),
                ('race', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='event.race')),
            ],
        ),
        migrations.AddField(
            model_name='athlete',
            name='special_price_option',
            field=models.ForeignKey(blank=True, help_text='Chosen special price for this athlete', null=True, on_delete=django.db.models.deletion.SET_NULL, to='event.packagespecialprice'),
        ),
    ]
