# Generated by Django 5.1.7 on 2025-04-09 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0032_packagespecialprice_athlete_special_price_option'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athlete',
            name='bib_number',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='team',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='packageoption',
            name='options_string',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='race',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
