# Generated by Django 5.1.7 on 2025-04-07 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('working_hours', models.CharField(help_text='e.g. Mon–Fri 9am–5pm', max_length=255)),
            ],
        ),
    ]
