# Generated by Django 5.1.7 on 2025-04-07 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_tester'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tester',
        ),
    ]
